version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      # Memastikan aplikasi bisa konek ke Redis menggunakan env var
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
